//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursesEntities : DbContext
    {
        public CoursesEntities()
            : base("name=CoursesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Courses> Courses { get; set; }
        public DbSet<Departments> Departments { get; set; }
        public DbSet<LinkTable> LinkTable { get; set; }
        public DbSet<Specializtions> Specializtions { get; set; }
        public DbSet<CoursesDetails> CoursesDetails { get; set; }
        public DbSet<Years> Years { get; set; }
    }
}
