//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Years
    {
        public Years()
        {
            this.Departments = new HashSet<Departments>();
        }
    
        public int Id { get; set; }
        public string Year { get; set; }
    
        public virtual ICollection<Departments> Departments { get; set; }
    }
}
